# Describes the format for available heater/cooler services

set_active:
  name: Set active
  description: Turn heater/cooler device on or off.
  target:
    entity:
      domain: heater_cooler
  fields:
    active:
      name: Active
      description: New value of heater/cooler on or off.
      required: true
      selector:
        select:
          options:
            - label: "Active"
              value: 0
            - label: "Invactive"
              value: 1

set_target_state:
  name: Set target state
  description: Set target state for heater/cooler device.
  target:
    entity:
      domain: heater_cooler
  fields:
    target_state:
      name: Target State
      description: New value of target state.
      required: true
      selector:
        select:
          options:
            - label: "Auto"
              value: 0
            - label: "Cool"
              value: 1
            - label: "Heat"
              value: 2
