# Describes the format for available heater/cooler services

set_active:
  name: Set Active
  description: Turn heater/cooler device on or off.
  target:
    entity:
      domain: heater_cooler

set_target_state:
  name: Set Target State
  description: Set target HVAC operation mode for heater/cooler device.
  target:
    entity:
      domain: heater_cooler
  fields:
    target_state:
      name: HVAC mode
      description: New value of operation mode.
      selector:
        select:
          options:
            - label: "Auto"
              value: "0"
            - label: "Cool"
              value: "1"
            - label: "Heat"
              value: "2"

set_temperature:
  name: Set Temperature
  description: Set target temperature of heater/cooler device.
  target:
    entity:
      domain: heater_cooler
      supported_features:
        - heater_cooler.HeaterCoolerEntityFeature.TARGET_TEMPERATURE
  fields:
    temperature:
      name: Temperature
      description: New target temperature for HVAC.
      filter:
        supported_features:
          - heater_cooler.HeaterCoolerEntityFeature.TARGET_TEMPERATURE
      selector:
        number:
          min: 0
          max: 250
          step: 0.1
          mode: box
